.Dd $Mdocdate$
.Dt srm 1
.Os
.Sh NAME
.Nm srm
.Nd securely remove files
.Sh SYNOPSIS
.Nm srm
.Op Fl GPX
.Sh DESCRIPTION
.Nm srm
is a small program which overwrites files before deleting such files,
thereby hopefully preventing the recovery of such files.
.Pp
.Nm srm
is designed such that
.Nm srm
is
.Em mostly
compatible with the
.Nm srm
of
.An MATT GAUTHIER.
See
.Lk http://sourceforge.net/projects/srm/ "the project's Web page" .
.Sh OPTIONS
The options of
.Nm srm
are as follows:
.Bl -tag -width Ds
.It Fl G
.Nm srm
.Fl G
.Pa file Op ...
overwrites
.Pa file
et al. in accordance with the GUTMANN method.
.Pp
The Wikipedia article regarding this
method of data sanitisation is actually fairly decent.  See
.Lk http://en.wikipedia.org/wiki/Gutmann_method "Gutmann method" .
.It Fl P
.Nm srm
.Fl P
.Pa file Op ...
overwrites
.Pa file
et al. in accordance with OpenBSD's old
.Nm rm
.Fl P
functionality.
.Pa file
et al. are overwritten with bytes
.Sy 00 ,
then
.Sy FF ,
then
.Sy 00 .
.It Fl X
.Nm srm
.Fl X
.Ar y
.Pa file Op ...
overwrites
.Pa file
and cohorts with pseudorandom data
.Ar y
times.
.Ed
.Sh THANKS
Mad props to
.An MATT GAUTHIER
for the original
.Nm srm .
.Sh AUTHOR
.Em This
.Nm srm
is maintained by
.An Varik
.An Dq ARE YOU HAVING FUN YET?
.An Valefor
.Aq varikvalefor@aol.com .
